### ISSUE TITLE
`folder-open' icon is visibly shrunk

### ISSUE THREAD

**Issue by ThatIndividual** [snwh/moka-icon-theme#266]
Hey there Sam,

I must begin by thanking you for this great icon pack and for offering it (and more importantly), supporting it, free of charge.

I've come across a rather strange bug, see for yourself:
![output](https://cloud.githubusercontent.com/assets/8588995/17995247/1d67ea94-6b58-11e6-8d48-2b76d1250906.gif)

I have installed the Moka icon theme from the repository stated on your website. Of course, Faba is also installed, as far as I know that's where the folder icons are sourced from. Searching for the canonical "folder-open" in /usr/share/icons/Faba yields the following:
![screenshot from 2016-08-26 07-08-05](https://cloud.githubusercontent.com/assets/8588995/17995717/e898a64c-6b5b-11e6-9592-17fc25c583cf.png)

To make sure this quirk did not arise from some fault on my part, I spun up an Ubuntu 16.04 VM, vanilla, with stock Unity (that's what I'm running), and the bug persisted:
![output2](https://cloud.githubusercontent.com/assets/8588995/17995337/c6992650-6b58-11e6-8aa8-46c67350f287.gif)

**Comment by germanfr** [comment]
This is a [Faba](https://github.com/snwh/faba-icon-theme) issue. Moka does not have these folder icons.

Anyway, the problem is that the icons for folder-drag-accept are missing except for 24x24. That's why it appears that small. I've submitted a pull request that solves this in snwh/faba-icon-theme#60
