### ISSUE TITLE
Slack icon

### ISSUE THREAD

**Issue by rawsh** [snwh/moka-icon-theme#372]
- Slack
- team chat
- `slack`

![screenshot from 2017-11-14 15-09-03](https://user-images.githubusercontent.com/7035671/32805034-cbf70438-c94d-11e7-8366-4ff1b2a57617.png)

The default icon looks pretty good but it's the wrong size and such. A task icon for the system tray would be nice as well, the default looks like this:

![screenshot from 2017-11-14 15-10-30](https://user-images.githubusercontent.com/7035671/32805083-f8e4130a-c94d-11e7-9b46-bdef92a2e153.png)

**Comment by NikoKrause** [comment]
There is already a Slack icon in Moka:
https://github.com/snwh/moka-icon-theme/blob/master/Moka/96x96/web/web-slack.png

The problem is, that the Slack app points to:
```
Icon=/usr/share/pixmaps/slack.png
```

Slack needs to point to:
```
Icon=slack.png
```
instead, so the icon provided by the theme (Moka) can be used.

This has to be changed by Slack developers though.
You can write them a request: https://linuxmint-dev.slack.com/help/requests/new
